### ISSUE TITLE
Cannot log in the admin

### ISSUE THREAD

**Issue by fzaninotto** [api-platform/demo#150]
**API Platform version(s) affected**: online demo

**Description**  

I can't log in the online demo admin

**How to reproduce**  

1. go to https://demo-admin.api-platform.com/
2. Enter username and password from the hint
3. click on "sign in"

The result is a red toast message with the message "Authentication failed, please retry".

**Comment by alanpoulain** [comment]
Yes, it's because the API database regularly loses all data (and schema).
It's probably because the DB in K8s is lost because a pod fails or something like this but I have no more clue.

More information can be found here:
- https://github.com/api-platform/demo/tree/master/api/helm/api
- https://github.com/api-platform/demo/blob/master/ci/deploy

**Comment by dunglas** [comment]
It's because Postgres' persitence isn't enabled: https://github.com/api-platform/demo/blob/master/api/helm/api/values.yaml#L66-L67

Instead we need persistence, instead of using a Volume, we should switch to a managed Postgres (such as Google Cloud SQL or DigitalOcean Postgres).

**Comment by vincentchalamon** [comment]
Deployment has been fixed
