### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by roukmoute** [api-platform/demo#30]
I don't why but the current version doesn't work, only the first page:
- https://asciinema.org/a/d5Z76nREfzv0jdhqOQH9BkYjo
![image](https://user-images.githubusercontent.com/2140469/45047865-9bbaa800-b07a-11e8-864d-ce9e0057cd89.png)
![image](https://user-images.githubusercontent.com/2140469/45047785-55fddf80-b07a-11e8-8afc-15efb7738d0e.png)
![image](https://user-images.githubusercontent.com/2140469/45047811-6615bf00-b07a-11e8-81b6-e2d222f1368c.png)
![image](https://user-images.githubusercontent.com/2140469/45047836-7af25280-b07a-11e8-9d93-eeb825ac75f5.png)

Tested on 3 different computers, all on ubuntu.

**Comment by dunglas** [comment]
Can you paste the output of docker-compose logs?

**Comment by aaa2000** [comment]
The error `/tmp:5432 - no response` comes from https://github.com/api-platform/demo/blob/d72cce5351d8a8cd4e1c9676ea85897072af2758/api/docker/php/docker-entrypoint.sh#L17, I changed to `until bin/console doctrine:query:sql "SELECT 1" --quiet; do` and I executed `docker-compose exec php bin/console assets:install public` because the assets was not loaded when it is symlink.
